---
title: "Plotly_buttons"
author: "JAT"
date: "1/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r PLOTLY buttons and quantmod}

#https://plotly.com/r/custom-buttons/

library(plotly)
library(quantmod)

d <- quantmod::getSymbols("AAPL")

df <- data.frame(Date=index(AAPL),coredata(AAPL))

high_annotations <- list(
  x=df$Date[df$AAPL.High == max(df$AAPL.High)], 
  y=max(df$AAPL.High),
  xref='x', yref='y',
  text=paste0('High: $',max(df$AAPL.High)),
  ax=0, ay=-40
)

low_annotations <- list(
  x=df$Date[df$AAPL.Low == min(df$AAPL.Low)], 
  y=min(df$AAPL.Low),
  xref='x', yref='y',
  text=paste0('Low: $',min(df$AAPL.Low)),
  ax=0, ay=40
)

# updatemenus component
updatemenus <- list(
  list(
    active = -1,
    type= 'buttons',
    buttons = list(
      list(
        label = "High",
        method = "update",
        args = list(list(visible = c(FALSE, TRUE)),
                    list(title = "Apple High",
                         annotations = list(c(), high_annotations)))),
      list(
        label = "Low",
        method = "update",
        args = list(list(visible = c(TRUE, FALSE)),
                    list(title = "Apple Low",
                         annotations = list(low_annotations, c() )))),
      list(
        label = "Both",
        method = "update",
        args = list(list(visible = c(TRUE, TRUE)),
                    list(title = "Apple",
                         annotations = list(low_annotations, high_annotations)))),
      list(
        label = "Reset",
        method = "update",
        args = list(list(visible = c(TRUE, TRUE)),
                    list(title = "Apple",
                         annotations = list(c(), c())))))
  )
)

fig <- df %>% plot_ly(type = 'scatter', mode = 'lines') 
fig <- fig %>% add_lines(x=~Date, y=~AAPL.High, name="High",
            line=list(color="#33CFA5")) 
fig <- fig %>% add_lines(x=~Date, y=~AAPL.Low, name="Low",
            line=list(color="#F06A6A")) 

fig <- fig %>% layout(title = "Apple", showlegend=FALSE,
         xaxis=list(title="Date"),
         yaxis=list(title="Price ($)"),
         updatemenus=updatemenus)


fig


```


```{r}


library(plotly)
library(quantmod)

d <- quantmod::getSymbols("AAPL")

df <- data.frame(Date=index(AAPL),coredata(AAPL))


high_annotations <- list(
  x=df$Date[df$AAPL.High == max(df$AAPL.High)], 
  y=max(df$AAPL.High),
  xref='x', yref='y',
  text=paste0('High: $',max(df$AAPL.High)),
  ax=0, ay=-40
)

low_annotations <- list(
  x=df$Date[df$AAPL.Low == min(df$AAPL.Low)], 
  y=min(df$AAPL.Low),
  xref='x', yref='y',
  text=paste0('Low: $',min(df$AAPL.Low)),
  ax=0, ay=40
)

```



```{r}

max_age=100
age <- seq(1,max_age, length.out = 100)

inflation=0.02
savings=12000
expenses_retirement=15000
working_age=18
maturity_age=30
retirement_age=65


retirement_facts <- function(inflation,when, age, savings, expenses_retirement,working_age, maturity_age, retirement_age)
{
  
in_flow=c(rep(0, working_age),seq(0,savings,savings/(maturity_age-working_age-1)),rep(savings, retirement_age-maturity_age),rep(0, max_age-retirement_age))

#print(length(in_flow))

in_flow_theorical=c(rep(0, working_age),seq(0,savings,savings/(maturity_age-working_age-1)),rep(savings, max_age-maturity_age))

out_flow=c(rep(0, retirement_age),rep(savings, max_age-retirement_age))


real_savings=rep(0, 100)
theorical_savings=rep(0, 100)

for (i in 1:length(age)){
  #print(i)
  #print(in_flow[i])
  
  
  if (i==1){
  real_savings[i]=in_flow[i]+0*(1-inflation)
  theorical_savings[i]=real_savings[i]
  }else if (i<=retirement_age) {
    real_savings[i]=in_flow[i]+real_savings[i-1]*(1-inflation)
    theorical_savings[i]=in_flow_theorical[i]+theorical_savings[i-1]*(1-inflation)
  }
  else{
    real_savings[i]=real_savings[i-1]*(1-inflation)-out_flow[i]
    theorical_savings[i]=in_flow_theorical[i]+theorical_savings[i-1]*(1-inflation)
  }
}


df <- data.frame(age, in_flow,in_flow_theorical,out_flow,real_savings,theorical_savings)


###Plot theorical
 plot(df$age, df$theorical_savings, type = "b", pch = 19, 
     col = "red", xlab = "x", ylab = "y")
###
 
 ###Plot real
 plot(df$age[1:which(real_savings < 0)[1]], real_savings[1:which(real_savings < 0)[1]], type = "b", frame = FALSE, pch = 19, 
     col = "red", xlab = "years", ylab = "real_savings")
# Add a second line
lines(df$age[1:which(real_savings < 0)[1]], theorical_savings[1:which(real_savings < 0)[1]], pch = 18, col = "blue", type = "b", lty = 2)
###

 #return(df$real_savings[when])
return(df)
}

df2<-retirement_facts(0.02,60,age,12000,15000,18,30,65)

```


```{r}



# updatemenus component
updatemenus <- list(
  list(
    active = -1,
    type= 'buttons',
    buttons = list(
      list(
        label = "Real",
        method = "update",
        args = list(list(visible = c(FALSE, TRUE)),
                    list(title = "Real savings"))),
                         #,
                         #annotations = list(c(), high_annotations)))),
      list(
        label = "Theorical",
        method = "update",
        args = list(list(visible = c(TRUE, FALSE)),
                    list(title = "Theorical savings")))
                         #,
                         #annotations = list(low_annotations, c() ))))
   
  )
))

fig <- df2 %>% plot_ly(type = 'scatter', mode = 'lines') 
fig <- fig %>% add_lines(x=~age, y=~real_savings, name="real_savings",
            line=list(color="#33CFA5")) 
fig <- fig %>% add_lines(x=~age, y=~theorical_savings, name="theorical_savings",
            line=list(color="#F06A6A")) 

fig <- fig %>% layout(title = "Savings", showlegend=FALSE,
         xaxis=list(title="Age"),
         yaxis=list(title="Savings ($)"),
         updatemenus=updatemenus)
          

fig


```